version: "3.9"
services:
  app:
    image: alexkondr/guru-analyzer_of_books:latest
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}