"""del tokens

Revision ID: 541f9646698e
Revises: b11af75a9c09
Create Date: 2023-09-26 14:32:45.268593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f9646698e'
down_revision = 'b11af75a9c09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tokens_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tokens_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
