"""delete vector_db_name

Revision ID: 558df6998045
Revises: eee2b9819e21
Create Date: 2023-09-19 21:57:01.481589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558df6998045'
down_revision = 'eee2b9819e21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_vector_db_name', table_name='documents')
    op.drop_column('documents', 'vector_db_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('vector_db_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_documents_vector_db_name', 'documents', ['vector_db_name'], unique=False)
    # ### end Alembic commands ###
