"""del tokens_count

Revision ID: 938e7acf5908
Revises: 7c329bbda5fc
Create Date: 2023-09-26 09:31:08.915751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e7acf5908'
down_revision = '7c329bbda5fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tokens_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tokens_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
