"""add 1 tokens_count

Revision ID: b11af75a9c09
Revises: 938e7acf5908
Create Date: 2023-09-26 09:31:40.265251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11af75a9c09'
down_revision = '938e7acf5908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tokens_count', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tokens_count')
    # ### end Alembic commands ###
