"""bugfix

Revision ID: c49d9821e258
Revises: eee2b9819e21
Create Date: 2023-09-17 16:38:59.397425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49d9821e258'
down_revision = 'eee2b9819e21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
