"""add chathistory

Revision ID: eee2b9819e21
Revises: 68dcdfe2024b
Create Date: 2023-09-17 13:35:47.026289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee2b9819e21'
down_revision = '68dcdfe2024b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('vector_db_name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_documents_document_id', table_name='documents')
    op.create_index(op.f('ix_documents_vector_db_name'), 'documents', ['vector_db_name'], unique=True)
    op.drop_column('documents', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_vector_db_name'), table_name='documents')
    op.create_index('ix_documents_document_id', 'documents', ['document_id'], unique=False)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'vector_db_name')
    op.drop_column('documents', 'name')
    op.drop_table('chathistory')
    # ### end Alembic commands ###
